### ISSUE TITLE
Map error

### ISSUE THREAD

**Issue by jeanguybillard** [ololoepepe/ddos-express#2]
After installing your module for my express project, i get this error; 

/var/www/vhosts/project/node_modules/ddos-express/index.js:5
        rule.users = new Map;
                         ^
ReferenceError: Map is not defined
    at createRule (/var/www/vhosts/project/node_modules/ddos-express/index.js:5:26)
    at /var/www/vhosts/project/node_modules/ddos-express/index.js:51:24
    at Array.forEach (native)
    at module.exports (/var/www/vhosts/project/node_modules/ddos-express/index.js:48:56)
    at Object.<anonymous> (/var/www/vhosts/project/app.js:26:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by jeanguybillard** [comment]
Ugraded nodejs to v4.0.x, and it solved it.

**Comment by ololoepepe** [comment]
Thanks, I'll add a fallback to an object for nodejs older than 4.0.x.
